### ISSUE TITLE
Secrets Don't Get Passed into Experiment Method

### ISSUE THREAD

**Issue by ksolie** [chaostoolkit-incubator/chaostoolkit-gremlin#1]
When specifying  the secrets add the top of the experiment, they don't get passed in as parameters when you issue the `attack` action. I am seeing the following when I specify the secrets at the top of the experiment, with a `print(secrets)` debug in the init method:
```
[2018-03-19 20:19:46 INFO] Validating the experiment's syntax
[2018-03-19 20:19:46 INFO] Experiment looks valid
[2018-03-19 20:19:46 INFO] Running experiment: Can our system handle a node being CPU-busy?
[2018-03-19 20:19:46 INFO] No steady state hypothesis defined. That's ok, just exploring.
[2018-03-19 20:19:46 INFO] Action: gremlin-test [in background]
None
[2018-03-19 20:17:42 ERROR]   => failed: TypeError: auth() argument after ** must be a mapping, not NoneType
[2018-03-19 20:19:46 INFO] No steady state hypothesis defined. That's ok, just exploring.

[2018-03-19 20:19:46 INFO] No declared rollbacks, let's move on.
[2018-03-19 20:19:46 INFO] Experiment ended with status: completed
```

When I specify the secrets in the method, I don't have any issues.

**Comment by Lawouach** [comment]
Hello,

Sorry for the lack of response. I'm wondering if you are setting the secrets value at the activity level that references the declaration from the top?

For instance: https://github.com/chaostoolkit/chaostoolkit-samples/blob/master/service-killed-not-visible-to-users/experiment.json#L62

If that's the case, there might be a bg indeed!

**Comment by ksolie** [comment]
I did specify the secrets that way but it still doesn't get passed into the arguments.

**Comment by Lawouach** [comment]
Indeed. That readme is totally wrong now.

I apologise, I forgot to update it. Let me do that.

**Comment by Lawouach** [comment]
Updated. I had forgotten this README. Sorry.

The structure matches the API now http://chaostoolkit.org/reference/api/experiment/#environment-secrets

Could you please try again?

**Comment by ksolie** [comment]
I tried it again and still am getting `NoneType` when it executes the attack action from `actions.py`

I also copied the example exactly (with the addition of a `name` value in the method which is required) and got the same issue

**Comment by ksolie** [comment]
Found the issue:
secrets["gremlin"] has to be passed in the `provider` of the `method` like so:
```
"method": [
        {
            "title": "attack-on-cpu",
            "type": "action",
            "background": true
            "provider": {
                "type": "python",
                "secrets": ["gremlin"],
                "module": "chaosgremlin.actions",
                "func": "attack",
                "arguments": {
                    "command": {
                        "type": "cpu"
                    },
                    "target": {
                        "type": "Random"
                    }
                }
            }
        }
    ]
```

**Comment by Lawouach** [comment]
Oh darn! I am so sorry for wasting your time!

Maybe a good warning to add to chaostoolkit when validating the experiment, don't you think?

**Comment by ksolie** [comment]
Yeah I think it would be a nice check

**Comment by Lawouach** [comment]
Thank you for your patience and sticking with it!

Good eyes as well ;)

**Comment by SudoQ** [comment]
Close this? README is updated with a working example. Any validation of experiments should be part of the core if this is not already resolved.

**Comment by ksolie** [comment]
@SudoQ , I think we can close this.

**Comment by Lawouach** [comment]
Agreed.
